name: Build and Deploy Vite to GitHub Pages

on:
    push:
        branches: [main, 2.0]
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build project
              run: bun run build
              env:
                  GITHUB_REPOSITORY: ${{ github.repository }}

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
