name: Build and Deploy
"on":
    push:
        branches:
            - main
    workflow_dispatch: null

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        name: Build Vite Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build project
              run: bun run build
              env:
                  GITHUB_REPOSITORY: "${{ github.repository }}"

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vite-build-output
                  path: ./dist

    prepare_deployment:
        name: Prepare Deployment Files
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: vite-build-output
                  path: ./dist

            - name: Modify dist for root redirect
              run: |
                  if [ -f ./dist/index.html ]; then
                    mv ./dist/index.html ./dist/app.html
                    echo "Renamed original index.html to app.html"
                  fi

                  echo '<!DOCTYPE html>
                  <html>
                  <head>
                    <meta charset="utf-8">
                    <title>Redirecting...</title>
                    <link rel="canonical" href="https://github.com/${{ github.repository }}"/>
                    <meta http-equiv="refresh" content="0; url=https://github.com/${{ github.repository }}">
                  </head>
                  <body>
                  </body>
                  </html>' > ./dist/index.html
                  echo "Created redirecting index.html"

            - name: Upload deployment artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deployment-package
                  path: ./dist

    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        needs: prepare_deployment
        steps:
            - name: Download deployment artifact
              uses: actions/download-artifact@v4
              with:
                  name: deployment-package
                  path: ./dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: "${{ secrets.GITHUB_TOKEN }}"
                  publish_dir: ./dist
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
